[package]
name = "anilib"
version = "26.0.0"
edition = "2024"
description = "Astry's Narrower Inkwell Library"
repository = "https://github.com/Censera/ani"
documentation = "https://docs.rs/ani"
readme = "README.md"
license = "Apache-2.0"
keywords = ["llvm", "compiler", "codegen"]
categories = ["development-tools::ffi"]

[lib]
name = "anilib"
path = "src/lib.rs"

[dependencies]
llvm-sys = "221.0.0"
