[package]
name = "an-inkwell"
version = "26.0.0"
edition = "2024"
description = "astry's Narrower Inkwell"
repository = "https://github.com/Censera/an-inkwell"
documentation = "https://docs.rs/an-inkwell"
readme = "README.md"
license = "Apache-2.0"
keywords = ["llvm", "compiler", "codegen"]
categories = ["development-tools::ffi"]

[lib]
name = "an_inkwell"
path = "src/lib.rs"

[dependencies]
llvm-sys = "221.0.0"
